# Generated by Django 4.2.6 on 2023-12-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='binding_type',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
